In [21]:
!pip install -U kaleido

In [2]:
import plotly.graph_objects as go
from plotly.io import write_image
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('/content/Biomodels cell cycles - Sheet2 (4).csv')

In [3]:
time = df['Time Complete'].to_list()

In [4]:
time_temp = []
for j in time:
  j = j.replace(",", "")
  if float(j) < 1:
    time_temp.append(float(j))
  else:
    time_temp.append(int(j))

In [5]:
df['Time Complete exp']  = time_temp

In [6]:
col = df.columns
col

Index([' ', 'No. of SORs', 'No. of Dos', '2a. No. of Reactions',
       '2b. No. of Species', '2c. Reactions / Species',
       '3a. No. of Organisations',
       '3b. Avg number of reactions per Organization', '3c. Height',
       '3e. Persistence', '3d. Width', '4a. No. of Genuine DOs',
       '4b. No. of Compartmentalized organisations',
       '4c. No. of Compartmentalizations', 'Time Complete',
       'No: of Compartments', 'Type of modelling tech', 'Organisms', 'Year',
       'Other Details', 'Part of cell cycle ', 'Time Complete exp'],
      dtype='object')

In [7]:
df['Time Complete exp']

0      2.273180e+16
1      1.878428e+16
2      2.652073e+16
3      1.053119e+16
4      2.685787e+16
           ...     
269    1.333473e+15
270    2.750134e+16
271    2.066113e+16
272    2.540851e+16
273    8.725333e+15
Name: Time Complete exp, Length: 274, dtype: float64

In [9]:
import plotly.graph_objects as go
import numpy as np

df['Time Complete Divided'] = df['Time Complete exp']/10**16

bins = [-5, 0, 5, 10, 15, 20]

hist, bin_edges = np.histogram(np.log10(df['Time Complete exp']), bins)
# Create plotly histogram
fig = go.Figure()

# Add histogram trace
fig.add_trace(go.Bar(
    x=[f"{bins[i]} - {bins[i+1]}" for i in range(len(bins) - 1)],
    y=hist,
    marker_color='rgb(55,168,55)',
    opacity=0.7,
    name='Time Taken'
))

# Update layout
fig.update_layout(
    title='Histogram with Time Taken to run',
    xaxis=dict(title='Time Taken (x10^16) Milliseconds'),
    yaxis=dict(title='Number of Models')
)

fig.update_layout(font=dict(size=18))

/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:396: RuntimeWarning:

divide by zero encountered in log10



In [11]:

import plotly.graph_objects as go
import numpy as np

df['Time Complete Divided'] = df['Time Complete exp']/10**16

bins = [0, 0.01, 0.02, 0.05, 0.08, 0.1, 0.2, 0.5, 0.75, 1, 1.2, 1.5, 2, 5, 7]

hist, bin_edges = np.histogram(df['Time Complete Divided'], bins)
# Create plotly histogram
fig = go.Figure()

# Add histogram trace
fig.add_trace(go.Bar(
    x=[f"{bins[i]} - {bins[i+1]}" for i in range(len(bins) - 1)],
    y=hist,
    marker_color='rgb(72,158,72)',
    opacity=0.7,
    name='Time Taken'
))

# Update layout
fig.update_layout(
    title='Histogram of time taken to run cell cycle models',
    xaxis=dict(title='Time Taken (x10^16) Milliseconds'),
    yaxis=dict(title='Number of Models'),
    title_x=0.5,
    title_y=0.95
)

fig.update_layout(font=dict(size=16))
fig.update_xaxes(showgrid=False)
fig.update_yaxes(showgrid=False)

write_image(fig, 'Histogram of Time Taken to run.png')

# Show plot
fig.show()

In [13]:
import plotly.graph_objects as go
import numpy as np

bins = [1, 2, 3, 4, 5, 10, 50, 100, 1000, 10000]

hist, bin_edges = np.histogram(df['No. of SORs'], bins)
hist2, bin_edges = np.histogram(df['4a. No. of Genuine DOs'], bins)

# Create plotly histogram
fig = go.Figure()

# Add histogram trace
fig.add_trace(go.Bar(
    x=[f"{bins[i]} - {bins[i+1]}" for i in range(len(bins) - 1)],
    y=hist,
    marker_color='rgb(72,158,72)',
    opacity=0.7,
    name='All Organizations'
))

fig.add_trace(go.Bar(
    x=[f"{bins[i]} - {bins[i+1]}" for i in range(len(bins) - 1)],
    y=hist2,
    marker_color='green',
    opacity=1,
    name='Organizations with more than one compartment'))

# Update layout
fig.update_layout(
    title='Fraction of organizations requiring more than one compartment',
    xaxis=dict(title='Number of Organizations'),
    yaxis=dict(title='Number of Models'),
    barmode='overlay',
    title_x=0.5,
    title_y=0.95
)

fig.update_layout(
    legend=dict(
        orientation="h",
        yanchor="bottom",
        y=1.02,
        xanchor="right",
        x=1
    )
)

fig.update_xaxes(tickvals=[f"{bins[i]} - {bins[i+1]}" for i in range(len(bins) - 1)], ticktext=['1', '2', '3', '4', '5-10', '10-50', '50-100', '1000+'], showgrid=False)
fig.update_yaxes(showgrid=False)

fig.update_layout(font=dict(size=16))

# Show plot
fig.show()

write_image(fig, 'Parameter 4a: Organizations versus those with multiple compartments.png', scale=5)

In [ ]:
df.columns

Index(['Unnamed: 0', 'No. of SORs', 'No. of Dos', '2a. No. of Reactions',
       '2b. No. of Species', '2c. Reactions / Species',
       '3a. No. of Organisations',
       '3b. Avg number of reactions per Organization', '3c. Height',
       '3e. Persistence', '3d. Width', '4a. No. of Genuine DOs',
       '4b. No. of Compartmentalized organisations',
       '4c. No. of Compartmentalizations', 'Time Complete',
       'No: of Compartments', 'Type of modelling tech', 'Organisms', 'Year',
       'Other Details', 'Part of cell cycle ', 'Time Complete exp',
       'Time Complete Divided'],
      dtype='object')

In [14]:
x = df['4c. No. of Compartmentalizations'].to_list()

for i in range(len(x)):
  x[i] = x[i]+1

df['4c. No. of Compartmentalizations'] = x

In [15]:
import plotly.graph_objects as go
import numpy as np

bins = [1, 2, 3, 4, 5, 10000]

hist, bin_edges = np.histogram(df['No: of Compartments'], bins)

# Create plotly histogram
fig = go.Figure()

# Add histogram trace
fig.add_trace(go.Bar(
    x=[f"{bins[i]} - {bins[i+1]}" for i in range(len(bins) - 1)],
    y=hist,
    marker_color='rgb(72,158,72)',
    opacity=0.7
))


# Update layout
fig.update_layout(
    title='Histogram of Organizations with No. of compartments',
    xaxis=dict(title='No. of required compartments'),
    yaxis=dict(title='No. of Models'),
    barmode='overlay',
    title_x=0.5,
    title_y=0.95
)

# Update x-axis labels
fig.update_xaxes(tickvals=[f"{bins[i]} - {bins[i+1]}" for i in range(len(bins) - 1)], ticktext=['1', '2', '3', '4', '5+'], showgrid=False)
fig.update_yaxes(showgrid=False)
fig.update_layout(font=dict(size=16))

# Show plot
fig.show()

write_image(fig, 'Parameter 4c: Histogram with Organisations with No. of compartments.png')

In [ ]:
import plotly.graph_objects as go
import numpy as np

bins = [1, 1.25, 1.5, 2, 3, 4, 5, 10, 50]

hist, bin_edges = np.histogram(np.log10(df['No. of SORs']), bins)
hist2, bin_edges = np.histogram(np.log10(df['No. of Dos']), bins)

# Create plotly histogram
fig = go.Figure()

# Add histogram trace
fig.add_trace(go.Bar(
    x=[f"{bins[i]} - {bins[i+1]}" for i in range(len(bins) - 1)],
    y=hist,
    marker_color='blue',
    opacity=0.7,
    name='No. of SORs'
))

fig.add_trace(go.Bar(
    x=[f"{bins[i]} - {bins[i+1]}" for i in range(len(bins) - 1)],
    y=hist2,
    marker_color='skyblue',
    opacity=0.7,
    name='No. of DOs'))

# Update layout
fig.update_layout(
    title='Histogram with SORs vs DOs',
    xaxis=dict(title='No. of SORs'),
    yaxis=dict(title='Count'),
    barmode='overlay'
)

# Show plot
fig.show()

In [ ]:
import plotly.express as px
fig = px.scatter(x=np.log10(df['No. of SORs']), y=np.log10(df['No. of Dos']))

fig.update_layout(
    title='SORs vs DOs Log10',
    xaxis=dict(title='No. of SORs'),
    yaxis=dict(title='No. of DOs')
)

fig.show()

In [ ]:
###IGNORE GRAPH
import plotly.graph_objects as go
import numpy as np

bins = [1, 2, 4, 7, 10, 15, 20, 30, 40, 50, 100, 1000, 10000]

hist, bin_edges = np.histogram(df['No. of SORs'], bins)
hist2, bin_edges = np.histogram(df['2a. No. of Reactions'], bins)
hist3, bin_edges = np.histogram(df['2b. No. of Species'], bins)
hist4, bin_edges = np.histogram(df['4a. No. of Genuine DOs'], bins)
hist5, bin_edges = np.histogram(df['3a. No. of Organisations'], bins)
# Create plotly histogram
fig = go.Figure()

# Add histogram trace
fig.add_trace(go.Bar(
    x=[f"{bins[i]} - {bins[i+1]}" for i in range(len(bins) - 1)],
    y=hist,
    marker_color='blue',
    opacity=0.7,
    name='No. of SORs'
))

fig.add_trace(go.Bar(
    x=[f"{bins[i]} - {bins[i+1]}" for i in range(len(bins) - 1)],
    y=hist2,
    name='No. of Reactions'))

fig.add_trace(go.Bar(
    x=[f"{bins[i]} - {bins[i+1]}" for i in range(len(bins) - 1)],
    y=hist3,
    name='No. of Species'))

fig.add_trace(go.Bar(
    x=[f"{bins[i]} - {bins[i+1]}" for i in range(len(bins) - 1)],
    y=hist4,
    name='No. of Genuine DOs'))

fig.add_trace(go.Bar(
    x=[f"{bins[i]} - {bins[i+1]}" for i in range(len(bins) - 1)],
    y=hist5,
    name='No. of Compartments'))

# Update layout
fig.update_layout(
    title='SORs vs Reactions vs Species vs Genuine DOs vs Organisations',
    xaxis=dict(title='No. of SORs'),
    yaxis=dict(title='Count')
)

# Show plot
fig.show()

In [16]:
col

Index([' ', 'No. of SORs', 'No. of Dos', '2a. No. of Reactions',
       '2b. No. of Species', '2c. Reactions / Species',
       '3a. No. of Organisations',
       '3b. Avg number of reactions per Organization', '3c. Height',
       '3e. Persistence', '3d. Width', '4a. No. of Genuine DOs',
       '4b. No. of Compartmentalized organisations',
       '4c. No. of Compartmentalizations', 'Time Complete',
       'No: of Compartments', 'Type of modelling tech', 'Organisms', 'Year',
       'Other Details', 'Part of cell cycle ', 'Time Complete exp'],
      dtype='object')

In [ ]:
#Parameters 2
import plotly.express as px
fig = px.scatter(x=np.log10(df['2b. No. of Species']), y=np.log10(df['2a. No. of Reactions']))

fig.update_layout(
    title='Number of Reactions vs Species',
    xaxis=dict(title='No. of Species'),
    yaxis=dict(title='No. of Reactions'),
    title_x=0.5,
    title_y=0.95
)


fig.update_xaxes(tickvals=[0, 1, 2], ticktext=[f'$10^{power}$' for power in np.arange(0,3)], showgrid=False)
fig.update_yaxes(tickvals=[1, 2, 3], ticktext=[f'$10^{power}$' for power in np.arange(1,3)], showgrid=False)


fig.update_layout(font=dict(size=16))

fig.show()

write_image(fig, 'Parameter 2: Reactions vs Species.png')

In [ ]:
#Parameter 3a
import plotly.graph_objects as go
import numpy as np

bins = [1, 2, 3, 4, 5, 10, 100, 10000]

hist, bin_edges = np.histogram(df['3a. No. of Organisations'], bins)

# Create plotly histogram
fig = go.Figure()

# Add histogram trace
fig.add_trace(go.Bar(
    x=[f"{bins[i]} - {bins[i+1]}" for i in range(len(bins) - 1)],
    y=hist,
    marker_color='blue',
    opacity=0.7
))


# Update layout
fig.update_layout(
    title='Histogram of the count of models along with number of organizations',
    xaxis=dict(title='No. of Organizations'),
    yaxis=dict(title='No. of Models'),
    barmode='overlay',
    title_x=0.5,
    title_y=0.95
)

# Update x-axis labels
fig.update_xaxes(tickvals=[f"{bins[i]} - {bins[i+1]}" for i in range(len(bins) - 1)], ticktext=['1', '2', '3', '4', '5-9', '10-99', '100+'], showgrid=False)
fig.update_yaxes(showgrid=False)

fig.update_layout(font=dict(size=16))

# Show plot
fig.show()

write_image(fig, 'Parameter 3a: Histogram of the count of models along with number of organizations.png')

In [ ]:
df.columns

Index(['Unnamed: 0', 'No. of SORs', 'No. of Dos', '2a. No. of Reactions',
       '2b. No. of Species', '2c. Reactions / Species',
       '3a. No. of Organisations',
       '3b. Avg number of reactions per Organization', '3c. Height',
       '3e. Persistence', '3d. Width', '4a. No. of Genuine DOs',
       '4b. No. of Compartmentalized organisations',
       '4c. No. of Compartmentalizations', 'Time Complete',
       'No: of Compartments', 'Type of modelling tech', 'Organisms', 'Year',
       'Other Details', 'Part of cell cycle ', 'Time Complete exp',
       'Time Complete Divided'],
      dtype='object')

In [ ]:
#Parameters 3b
import plotly.express as px
fig = px.scatter(x=np.log10(df['No. of SORs']), y=np.log10(df['2a. No. of Reactions']))

fig.update_layout(
    title='Organizations vs No. of Reactions',
    xaxis=dict(title='No. of Organizations'),
    yaxis=dict(title='No. of Reactions'),
    title_x=0.5,
    title_y=0.95
)

fig.update_xaxes(tickvals=[0, 1, 2, 3, 4, 5], ticktext=[f'$10^{power}$' for power in np.arange(0,5)], showgrid=False)
fig.update_yaxes(tickvals=[0, 1, 2, 3], ticktext=[f'$10^{power}$' for power in np.arange(0,3)], showgrid=False)

fig.update_layout(font=dict(size=16))

fig.show()

write_image(fig, 'Parameter 3b: Organizations vs No. of Reactions.png')

In [ ]:
f'$10^{16}$'

'$10^16$'

In [ ]:
import plotly.graph_objs as go
import numpy as np

# Calculate counts for each data point
unique_points, counts = np.unique(list(zip(df['3c. Height'], df['3d. Width'])), axis=0, return_counts=True)

y = df['3d. Width']
y = [i for i in y if i!=56]

# Create scatter plot
scatter = go.Scatter(
    x=df['3c. Height'],
    y=y,
    mode='markers',
    marker=dict(
        size=10,
        color=counts,
        opacity=0.7,
        colorbar=dict(title='Count')
    )
)

# Create layout
layout = go.Layout(
    title='Scatter Plot with Clipped Counts as Marker Color',
    xaxis=dict(title='X-axis'),
    yaxis=dict(title='Y-axis')
)
fig = go.Figure(data=[scatter], layout=layout)

fig.update_layout(
    title='Height vs Width of lattice of models',
    xaxis=dict(title='Height'),
    yaxis=dict(title='Width'),
    title_x=0.5,
    title_y=0.95
)

fig.update_layout(font=dict(size=16))

# Create figure
fig.show()
#write_image(fig, 'Parameter 3c&d: Height vs Width Scatter.png')

In [ ]:
x = df['3c. Height']
y = df['3d. Width']

print(df[df['3d. Width'] == 56].index)

x = df['3c. Height'].drop(69)
y = df['3d. Width'].drop(69)

Index([69], dtype='int64')


In [23]:
import plotly.graph_objects as go
import numpy as np


xedges = np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
yedges = np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21])

hist, xedges, yedges = np.histogram2d(x, y, bins=[xedges, yedges])
hist = hist.astype(int)
# Compute logarithmic values for color intensity
log_hist = np.log1p(hist)  # Use log1p to avoid log(0) issues

# Create the heatmap
fig = go.Figure(data=go.Heatmap(
    x=xedges,
    y=yedges,
    z=hist.T,  # Transpose the histogram for correct orientation
    colorscale='Viridis',  # Choose your desired colorscale
))

fig.update_layout(
    title='Height vs Width of lattice of models',
    xaxis=dict(title='Height'),
    yaxis=dict(title='Width'),
    title_x=0.5,
    title_y=0.95,
    height=800   # Set the height of the graph
)

# Add annotations to display the counts inside the plot
annotations = []
for i in range(len(xedges)-1):
    for j in range(len(yedges)-1):
        annotations.append(
            dict(
                x=(xedges[i] + xedges[i+1]) / 2 ,
                y=(yedges[j] + yedges[j+1]) / 2 ,
                text=str(hist[i, j]),
                showarrow=False,
                font=dict(color='black' if log_hist[i, j] >= 0 else 'black')
            )
        )

fig.update_layout(annotations=annotations)

fig.update_layout(xaxis=dict(
    tickvals=(xedges[:-1] + xedges[1:]) / 2,  # Specify the positions of the x-axis ticks at bin centers
    ticktext=xedges
))
fig.update_layout(yaxis=dict(
    tickvals=(yedges[:-1] + yedges[1:]) / 2,  # Specify the positions of the y-axis ticks at bin centers
    ticktext=yedges
))

fig.update_traces(colorscale=[[0, 'rgba(255,255,255,255)'], [1, 'rgba(68,70,251,255)']] , zmin=0, zmax=25)

fig.update_layout(font=dict(size=16))

# Show plot
fig.show()

write_image(fig, 'Parameter 3c&d: Height vs Width Heatmap.png')

In [ ]:
import numpy as np

# Example arrays
array1 = x
array2 = y

# Get unique values in both arrays
unique_values = np.union1d(array1, array2)

# Initialize the 2D matrix to store the counts
count_matrix = np.zeros((len(unique_values), len(unique_values)), dtype=int)

# Count occurrences
for i, val1 in enumerate(unique_values):
    for j, val2 in enumerate(unique_values):
        count_matrix[i, j] = np.sum((array1 == val1) & (array2 == val2))

# Print the 2D matrix
print("Count matrix:")
print(count_matrix)

Count matrix:
[[ 46  13   2   0   0   1   0   0   0   0   1   0   0   0   1   0]
 [  6 135   0   3   1   1   0   1   0   0   0   0   0   0   0   0]
 [  5  15   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  1   4   2   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  1   6   1   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   1   0   0   0   0   3   0   0   0   0   0   0   0   0   0]
 [  1   1   0   1   0   1   1   0   1   0   0   0   0   1   0   0]
 [  2   1   0   1   0   1   0   0   0   0   0   0   0   1   0   0]
 [  0   3   0   0   0   0   1   0   0   0   0   0   0   0   0   0]
 [  0   1   0   0   0   0   0   0   0   0   0   0   0   0   1   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   2   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   

In [ ]:
unique_values

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 13., 15.,
       20., 22., nan])

In [ ]:
(xedges[:-1] + xedges[1:]) / 2

array([ 0.5,  1.5,  2.5,  3.5,  4.5,  5.5,  6.5,  7.5,  8.5,  9.5, 10.5,
       11.5, 12.5, 13.5, 14.5])

In [ ]:
xedges

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
counts

array([ 59,   2,   1,   1,   1, 141,   3,   1,   1,   1,  20,   5,   2,
         7,   1,   1,   3,   2,   1,   1,   1,   1,   1,   3,   1,   1,
         1,   4,   1,   1,   1,   1,   2])

In [ ]:
#Parameters 3c&d
import plotly.express as px
fig = px.scatter(x=df['3c. Height'], y=df['3d. Width'])

fig.update_layout(
    title='Height vs Width of lattice of models',
    xaxis=dict(title='Height'),
    yaxis=dict(title='Width'),
    title_x=0.5,
    title_y=0.95
)

#fig.update_xaxes(tickvals=[0, 1, 2], ticktext=[f'$10^{power}$' for power in np.arange(0,2)], showgrid=False)
#fig.update_yaxes(tickvals=[0, 1, 2], ticktext=[f'$10^{power}$' for power in np.arange(0,2)], showgrid=False)
#fig.update_layout(font=dict(size=16))

fig.update_layout(font=dict(size=16))

fig.show()

#STILL HAVE TO PLOT
#write_image(fig, 'Parameter 3c&d: Height vs Width.png')

In [ ]:
#Parameter 3a
import plotly.graph_objects as go
import numpy as np

bins = [1, 2, 3, 4, 5, 100]

hist, bin_edges = np.histogram(df['3c. Height'], bins)

# Create plotly histogram
fig = go.Figure()

# Add histogram trace
fig.add_trace(go.Bar(
    x=[f"{bins[i]} - {bins[i+1]}" for i in range(len(bins) - 1)],
    y=hist,
    marker_color='blue',
    opacity=0.7
))


# Update layout
fig.update_layout(
    title='Histogram of Height of lattices along with number of models',
    xaxis=dict(title='Height of lattice'),
    yaxis=dict(title='No. of Models'),
    barmode='overlay',
    title_x=0.5,
    title_y=0.95
)

# Update x-axis labels
fig.update_xaxes(tickvals=[f"{bins[i]} - {bins[i+1]}" for i in range(len(bins) - 1)], ticktext=['1', '2', '3', '4', '5+'], showgrid=False)
fig.update_yaxes(showgrid=False)

fig.update_layout(font=dict(size=16))

# Show plot
fig.show()

write_image(fig, 'Parameter 3c: Height.png')

In [ ]:
#Parameter 3a
import plotly.graph_objects as go
import numpy as np

bins = [1, 2, 3, 4, 5, 100]

hist, bin_edges = np.histogram(df['3d. Width'], bins)

# Create plotly histogram
fig = go.Figure()

# Add histogram trace
fig.add_trace(go.Bar(
    x=[f"{bins[i]} - {bins[i+1]}" for i in range(len(bins) - 1)],
    y=hist,
    marker_color='blue',
    opacity=0.7
))


# Update layout
fig.update_layout(
    title='Histogram of Width of lattices along with number of models',
    xaxis=dict(title='Width of lattice'),
    yaxis=dict(title='No. of Models'),
    barmode='overlay',
    title_x=0.5,
    title_y=0.95
)

# Update x-axis labels
fig.update_xaxes(tickvals=[f"{bins[i]} - {bins[i+1]}" for i in range(len(bins) - 1)], ticktext=['1', '2', '3', '4', '5+'], showgrid=False)
fig.update_yaxes(showgrid=False)

fig.update_layout(font=dict(size=16))

# Show plot
fig.show()

write_image(fig, 'Parameter 3d: Width.png')

In [ ]:
import plotly.graph_objs as go
import numpy as np

# Generate data
x_data = np.arange(1, 5)
y_data = [10, 100, 1000, 10000]

# Create plot
fig = go.Figure()

# Add trace
fig.add_trace(go.Scatter(x=x_data, y=y_data, mode='lines'))

# Define the powers of 10 for x-axis labels
powers_of_10 = np.arange(1, 5)

# Generate the corresponding labels for powers of 10
x_labels = [f'$10^{power}$' for power in np.arange(1, 5)]

# Update x-axis labels
fig.update_xaxes(tickvals=x_data, ticktext=x_labels)

# Show plot
fig.show()

In [ ]:
df.columns

Index(['Unnamed: 0', 'No. of SORs', 'No. of Dos', '2a. No. of Reactions',
       '2b. No. of Species', '2c. Reactions / Species',
       '3a. No. of Organisations',
       '3b. Avg number of reactions per Organization', '3c. Height',
       '3e. Persistence', '3d. Width', '4a. No. of Genuine DOs',
       '4b. No. of Compartmentalized organisations',
       '4c. No. of Compartmentalizations', 'Time Complete',
       'No: of Compartments', 'Type of modelling tech', 'Organisms', 'Year',
       'Other Details', 'Part of cell cycle ', 'Time Complete exp',
       'Time Complete Divided'],
      dtype='object')

In [ ]:
#Parameters 3e
import plotly.graph_objects as go
import numpy as np

bins = [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 2]

hist, bin_edges = np.histogram(df['3e. Persistence'], bins)
# Create plotly histogram
fig = go.Figure()

# Add histogram trace
fig.add_trace(go.Bar(
    x=[f"{bins[i]} - {bins[i+1]}" for i in range(len(bins) - 1)],
    y=np.log10(hist),
    marker_color='blue',
    opacity=0.7,
    name='Persistence'
))


# Update layout
fig.update_layout(
    title='Histogram of Persistence along with number of models',
    xaxis=dict(title='Persistence'),
    yaxis=dict(title='Number of Models'),
    title_x=0.5,
    title_y=0.92
)

fig.update_layout(font=dict(size=16))
fig.update_xaxes(tickvals=[f"{bins[i]} - {bins[i+1]}" for i in range(len(bins) - 1)], ticktext=['<0.1', '0.1', '0.2', '0.3', '0.4', '0.5', '0.6', '0.7', '0.8', '0.9', '1'], showgrid=False)
fig.update_yaxes(tickvals=[0, 1, 2, 3], ticktext=[f'$10^{power}$' for power in np.arange(0,3)], showgrid=False)
fig.show()

write_image(fig, 'Parameter 3e: Histogram of Persistence vs log10 of Number of models.png')

In [ ]:
#Parameters 3e
import plotly.express as px
fig = px.scatter(x=df['3e. Persistence'],  y=np.log10(df['3a. No. of Organisations']))

fig.update_layout(
    title='Parameter 3e: Scatter plot of Persistence vs Log10 of Organizations',
    xaxis=dict(title='Persistence'),
    yaxis=dict(title='Log10 of No. of Organizations'),
    title_x=0.5,
    title_y=0.95
)

fig.show()

write_image(fig, 'Parameter 3e: Scatter plot of Persistence vs Log10 of Organisations.png')

In [ ]:
import plotly.express as px
fig = px.scatter(x=np.log10(df['4a. No. of Genuine DOs']), y=np.log10(df['4c. No. of Compartmentalizations']))

fig.update_layout(
    title='No. of Genuine DOs vs Compartmentalizations',
    xaxis=dict(title='No. of Genuine DOs'),
    yaxis=dict(title='No. of Compartmentalizations'),
    title_x=0.5,
    title_y=0.95
)

fig.show()

write_image(fig, '4a and 4c No. of Genuine DOs vs Compartmentalizations.png')

/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:396: RuntimeWarning:

divide by zero encountered in log10



In [ ]:
import plotly.express as px
fig = px.scatter(x=np.log10(df['3a. No. of Organisations']), y=np.log10(df['4c. No. of Compartmentalizations']))

fig.update_layout(
    title='No. of Organizations vs No. of Compartmentalizations',
    xaxis=dict(title='No. of Organizations'),
    yaxis=dict(title='No. of Compartmentalizations'),
    title_x=0.5,
    title_y=0.95
)

fig.show()

write_image(fig, '3a & 4c No. of Organisations vs No. of Compartmentalizations.png')

In [ ]:
df.columns

Index(['Unnamed: 0', 'No. of SORs', 'No. of Dos', '2a. No. of Reactions',
       '2b. No. of Species', '2c. Reactions / Species',
       '3a. No. of Organisations',
       '3b. Avg number of reactions per Organization', '3c. Height',
       '3e. Persistence', '3d. Width', '4a. No. of Genuine DOs',
       '4b. No. of Compartmentalized organisations',
       '4c. No. of Compartmentalizations', 'Time Complete',
       'No: of Compartments', 'Type of modelling tech', 'Organisms', 'Year',
       'Other Details', 'Part of cell cycle ', 'Time Complete exp',
       'Time Complete Divided'],
      dtype='object')

In [ ]:
import plotly.express as px
fig = px.scatter(x=np.log10(df['No. of SORs']), y=np.log10(df['Time Complete exp']))

fig.update_layout(
    title='SORs vs Time Complete (milliseconds)',
    xaxis=dict(title='No. of SORs'),
    yaxis=dict(title='Time Complete (milliseconds)')
)

fig.show()

In [ ]:
import plotly.express as px
fig = px.scatter(x=np.log10(df['No. of Dos']), y=np.log10(df['Time Complete exp']))

fig.update_layout(
    title='DOs vs Time Complete',
    xaxis=dict(title='No. of Dos'),
    yaxis=dict(title='Time Complete')
)

fig.show()

In [ ]:
import plotly.express as px
fig = px.scatter(x=np.log10(df['4a. No. of Genuine DOs']), y=np.log10(df['Time Complete exp']))

fig.update_layout(
    title='Genuine DOs vs Time Complete',
    xaxis=dict(title='No. of Genuine Dos'),
    yaxis=dict(title='Time Complete'),
    title_x=0.5,
    title_y=0.95
)

fig.show()

write_image(fig, 'Genuine DOs vs Time Complete.png')

/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:396: RuntimeWarning:

divide by zero encountered in log10



In [ ]:
import plotly.express as px
fig = px.scatter(x=df['2a. No. of Reactions'], y=np.log10(df['Time Complete exp']))

fig.update_layout(
    title='No. of Reactions vs Time Complete',
    xaxis=dict(title='No. of Reactions'),
    yaxis=dict(title='Time Complete'),
    title_x=0.5,
    title_y=0.95
)


fig.update_layout(font=dict(size=16))
fig.update_xaxes(showgrid=False)
fig.update_yaxes(tickvals=[12, 13, 14, 15, 16, 17], ticktext=[f'$100^{power}$' for power in np.arange(2,8)], showgrid=False)
#fig.update_yaxes(tickvals=[0, 1, 2, 3, 4, 5, 6], ticktext=[f'$10^{power}$' for power in np.arange(0,7)], showgrid=False)
fig.show()


write_image(fig, '2a: No. of Reactions vs Time Complete.png')

/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:396: RuntimeWarning:

divide by zero encountered in log10



In [ ]:
[f'$10^{power}$' for power in np.arange(12,17)]

['$10^12$', '$10^13$', '$10^14$', '$10^15$', '$10^16$']

In [ ]:
import plotly.express as px
fig = px.scatter(x=df['2b. No. of Species'], y=np.log10(df['Time Complete exp']))

fig.update_layout(
    title='No. of Species vs Time Complete',
    xaxis=dict(title='No. of Species'),
    yaxis=dict(title='Time Complete'),
    title_x=0.5,
    title_y=0.95
)

fig.update_layout(font=dict(size=16))
fig.update_xaxes(showgrid=False)
fig.update_yaxes(tickvals=[12, 13, 14, 15, 16, 17], ticktext=[f'$100^{power}$' for power in np.arange(2,8)], showgrid=False)
#fig.update_yaxes(tickvals=[0, 1, 2, 3, 4, 5, 6], ticktext=[f'$10^{power}$' for power in np.arange(0,7)], showgrid=False)
fig.show()

write_image(fig, '2b: No. of Species vs Time Complete.png')

/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:396: RuntimeWarning:

divide by zero encountered in log10



In [ ]:
import plotly.express as px
fig = px.scatter(x=np.log10(df['3a. No. of Organisations']), y=np.log10(df['Time Complete exp']))

fig.update_layout(
    title='Organizations vs Time Complete',
    xaxis=dict(title='No. of Organizations'),
    yaxis=dict(title='Time Taken (milliseconds)'),
    title_x=0.5,
    title_y=0.95
)
fig.update_layout(font=dict(size=16))
fig.update_xaxes(showgrid=False)
fig.update_yaxes(tickvals=[12, 13, 14, 15, 16, 17], ticktext=[f'$100^{power}$' for power in np.arange(2,8)], showgrid=False)
#fig.update_yaxes(tickvals=[0, 1, 2, 3, 4, 5, 6], ticktext=[f'$10^{power}$' for power in np.arange(0,7)], showgrid=False)
fig.show()

write_image(fig, '3a: Organisations vs Time Complete.png')

/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:396: RuntimeWarning:

divide by zero encountered in log10



In [ ]:
import plotly.express as px
fig = px.scatter(x=np.log10(df['4c. No. of Compartmentalizations']), y=np.log10(df['Time Complete exp']))

fig.update_layout(
    title='Compartmentalizaions vs Time Complete',
    xaxis=dict(title='No. of Compartmentalizations'),
    yaxis=dict(title='Time Complete'),
    title_x=0.5,
    title_y=0.95
)

fig.update_layout(font=dict(size=16))
fig.update_xaxes(tickvals=[0, 1, 2, 3, 4], ticktext=[f'$10^{power}$' for power in np.arange(0,5)], showgrid=False)
fig.update_yaxes(tickvals=[12, 13, 14, 15, 16, 17], ticktext=[f'$100^{power}$' for power in np.arange(2,8)], showgrid=False)
#fig.update_yaxes(tickvals=[0, 1, 2, 3, 4, 5, 6], ticktext=[f'$10^{power}$' for power in np.arange(0,7)], showgrid=False)
fig.show()

write_image(fig, '4c: Compartmentalizaions vs Time Complete.png')

/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:396: RuntimeWarning:

divide by zero encountered in log10



In [ ]:
df.columns

Index(['Unnamed: 0', 'No. of SORs', 'No. of Dos', '2a. No. of Reactions',
       '2b. No. of Species', '2c. Reactions / Species',
       '3a. No. of Organisations',
       '3b. Avg number of reactions per Organization', '3c. Height',
       '3e. Persistence', '3d. Width', '4a. No. of Genuine DOs',
       '4b. No. of Compartmentalized organisations',
       '4c. No. of Compartmentalizations', 'Time Complete',
       'No: of Compartments', 'Type of modelling tech', 'Organisms', 'Year',
       'Other Details', 'Part of cell cycle ', 'Time Complete exp'],
      dtype='object')

In [ ]:
org = df['Organisms'].dropna().to_list()

In [ ]:
from collections import Counter

item_counts = Counter(org)
item_counts_dict = dict(item_counts)
print(item_counts_dict)

{'Amphibia': 4, 'Opisthokonta ': 3, 'Schizosaccharomyces pombe ': 4, 'Escherichia coli ': 2, 'Nicotiana tabacum ': 1, 'Drosophila melanogaster ': 2, 'Homo sapiens ': 49, 'Mesocricetus auratus  Drosophila melanogaster ': 1, 'Xenopus laevis ': 13, 'Oryctolagus ': 2, 'Arabidopsis ': 2, 'Saccharomyces cerevisiae ': 38, 'Escherichia coli K-12 ': 1, 'Mammalia ': 24, 'cellular organisms ': 8, 'Arabidopsis thaliana ': 4, 'Dictyostelium ': 1, 'Eukaryota ': 8, 'Schizosaccharomycetaceae ': 1, 'Cavia porcellus ': 1, 'Chordata ': 2, 'Rattus ': 1, 'Mycobacterium tuberculosis ': 1, 'Dictyostelium discoideum ': 1, 'Murinae ': 6, 'Viridiplantae ': 11, 'Bordetella pertussis  Homo sapiens ': 1, 'Mus musculus ': 5, 'Ostreococcus tauri ': 1, 'Viridiplantae  Mammalia ': 1, 'Arabidopsis thaliana': 1, 'Influenza A virus (A/Puerto Rico/8/1934(H1N1))  Influenza A virus  Mammalia ': 1, 'Mus ': 2, 'Vertebrata ': 1, 'Caulobacter vibrioides ': 2, 'unclassified eukaryotes ': 1, 'Danio rerio ': 1, 'Rattus norvegicus 

In [ ]:
item_counts = {key: value for key, value in item_counts_dict.items() if value != 1}

print(item_counts)

{'Amphibia': 4, 'Opisthokonta ': 3, 'Schizosaccharomyces pombe ': 4, 'Escherichia coli ': 2, 'Drosophila melanogaster ': 2, 'Homo sapiens ': 49, 'Xenopus laevis ': 13, 'Oryctolagus ': 2, 'Arabidopsis ': 2, 'Saccharomyces cerevisiae ': 38, 'Mammalia ': 24, 'cellular organisms ': 8, 'Arabidopsis thaliana ': 4, 'Eukaryota ': 8, 'Chordata ': 2, 'Murinae ': 6, 'Viridiplantae ': 11, 'Mus musculus ': 5, 'Mus ': 2, 'Caulobacter vibrioides ': 2}


In [ ]:
k = 0
for i in item_counts_dict.values():
  if i==1:
    k+=1
k

20

In [ ]:
item_counts['Other organisms'] = 20

In [ ]:
import plotly.graph_objects as go

item_counts = {k: v for k, v in sorted(item_counts.items(), key=lambda item: item[1], reverse=True)}

# Extracting class names and counts from dictionary
classes = list(item_counts.keys())
counts = list(item_counts.values())

# Create bar plot
fig = go.Figure(data=[go.Bar(x=classes, y=counts)])

# Update layout
fig.update_layout(
    title='Different types of Organisms',
    xaxis_title='Organisms',
    yaxis_title='No. of Models',
    title_x=0.5,
    title_y=0.95
)

fig.update_layout(font=dict(size=16))
fig.update_xaxes(showgrid=False)
fig.update_yaxes(showgrid=False)
# Show plot
fig.show()


write_image(fig, '1a: Different types of Organisms.png')

In [ ]:
import plotly.graph_objects as go

# Sample list of numbers
data = [1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 5]

# Create histogram
fig = go.Figure(data=[go.Histogram(x=df['No: of Compartments'])])

# Update layout
fig.update_layout(
    title='Histogram of Number of compartments in the models',
    xaxis_title='No. of compartments',
    yaxis_title='No. of Models',
    title_x=0.5,
    title_y=0.95
)

fig.update_layout(font=dict(size=16))
fig.update_xaxes(showgrid=False)
fig.update_yaxes(showgrid=False)
# Show plot
fig.show()


write_image(fig, '1e: Different types of Organisms.png')